project:
  type: website

website:
  title: "Math4Psychologists101"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Temario"
        href: syllabus.qmd
      - text: "Ponentes"
        href: about.qmd
format:
  html:
    theme: minty
    css: styles.css
